[package]
name = "embassy-usb-logger"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-usb = { version = "0.1.0", path = "../embassy-usb" }
embassy-sync = { version = "0.1.0", path = "../embassy-sync" }
embassy-futures = { version = "0.1.0", path = "../embassy-futures" }
futures = { version = "0.3", default-features = false }
static_cell = "1"
usbd-hid = "0.6.0"
log = "0.4"
